### ISSUE TITLE
certificate chain issue in firefox for openiban.com

### ISSUE THREAD

**Issue by htreu** [fourcube/goiban-service#1]
openiban.com is secured by an SSL/TLS certificate. This certificate has an [incomplete certification chain](https://www.ssllabs.com/ssltest/analyze.html?d=openiban.com). This lets firefox popup a certification warning and you have to manually add an exception. Chrome handles this issue just fine.
Another problem: When doing JavaScript CORS to openiban.com firefox refuses to connect due to the certificate error.

Tested with firefox 41.0.2

**Comment by fourcube** [comment]
Thank you for reporting this. I'll fix it tonight.
Am 03.11.2015 12:45 schrieb "Henning Treu" <notifications@github.com>:

**Comment by fourcube** [comment]
I have resolved the issue and also took this opportunity to bring the SSL cipher configuration of the server up to date. Thanks again for pointing this out!
