### ISSUE TITLE
IT IBAN false positive

### ISSUE THREAD

**Issue by pasqualedante** [fourcube/goiban-service#10]
Hi thanks for the great work!

I have a false positive for the IT IBAN IT96370400440532013000: open Iban get this response
{
  "valid": true,
  "messages": [],
  "iban": "IT96370400440532013000",
  "bankData": {
    "bankCode": "",
    "name": ""
  },
  "checkResults": {}
}
but the code isn't valid because Italy IBAN must have a length of 27 chars.

Ciao.

**Comment by fourcube** [comment]
Thank you for reporting this. I've just fixed it.
