### ISSUE TITLE
IBAN rule exception for the Commerzbank is not implemented

### ISSUE THREAD

**Issue by jaltek** [fourcube/goiban-service#17]
Hi,

according to the IBAN ruleset from the German Bundesbank there is an exception regarding the IBAN validation for IBANs from the Commerzbank. In this case goiban has to return the BIC "COBADEFFXXX" instead of "COBADEHHXXX" for example.

References:

https://www.willuhn.de/bugzilla/show_bug.cgi?id=1709
https://www.bankleitzahlen.ws/20040000

The ruleset itself is only avaible in the [Extranet](https://www.bundesbank.de/Navigation/DE/Service/Extranet/extranet.html) from the German Bundesbank (or Google for "iban regeln" :))

**Comment by fourcube** [comment]
Thank you for reporting this. I've just fixed it through

https://github.com/fourcube/goiban/commit/ec309dda2e3ebbbb851589f7d0be993f1824a9c9

**Comment by jaltek** [comment]
Awesome. Thanks a lot!
