### ISSUE TITLE
Missing CORS header in response

### ISSUE THREAD

**Issue by blacklord049** [fourcube/goiban-service#18]
Hi,

Unable to validate IBAN through an AJAX query. Missing header : Access-Control-Allow-Origin

Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://openiban.com/validate/BE30063934505311?validateBankCode=false&getBIC=true. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant.

Response header (260 o) |  

Date | Thu, 25 Jan 2018 11:58:34 GMT
Front-End-Https | on
Vary | Origin, Access-Control-Request…ccess-Control-Request-Headers

**Comment by fourcube** [comment]
Thank you for reporting this. I'll take a look at it.

**Comment by fourcube** [comment]
@blacklord049 please try again. I've added CORS headers to the response of the preflight request.

**Comment by blacklord049** [comment]
I got this error now : missing "jquery_request" token, but I don't know what this token is :-)

Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://openiban.com/validate/BE30063934505311?validateBankCode=false&getBIC=true. Raison : jeton « jquery_request » manquant dans l’en-tête CORS « Access-Control-Allow-Headers » du canal de pré-vérification des requêtes CORS.

**Comment by fourcube** [comment]
This means that the request sends an additional header called `jquery_request`. I've added it to the `Access-Control-Allow-Headers` response header. Could you try again please? If it still does not work, please send me the raw request (including all headers), so I can reproduce the issue.

**Comment by blacklord049** [comment]
It's working now, it correctly retrieves BIC information. 

![image](https://user-images.githubusercontent.com/16919700/35389082-9bfe3938-01d6-11e8-97c1-5c3f7d8e5d71.png)

**Comment by fourcube** [comment]
Ok, perfect. I'll close this issue.

**Comment by jsdevtom** [comment]
Hi @fourcube, thanks for your awesome service!

I am getting the same error:
### Error
```
Access to XMLHttpRequest at 'http://openiban.com/validate/DE89%203704%200044%200532%200130%2000?getBIC=true' from origin 'http://localhost:4201' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
### Request URL:
```
Request URL: http://openiban.com/validate/DE89%203704%200044%200532%200130%2000?getBIC=true
```

### Request headers:
```
GET /validate/DE89%203704%200044%200532%200130%2000?getBIC=true HTTP/1.1
Host: openiban.com
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Origin: http://localhost:4201
Referer: http://openiban.com/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
```

### Response headers:
```
HTTP/1.1 301 Moved Permanently
Date: Wed, 01 Jul 2020 19:24:38 GMT
Content-Type: text/html; charset=iso-8859-1
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=dd536f520b2e66f3f1636e176765a61871593631478; expires=Fri, 31-Jul-20 19:24:38 GMT; path=/; domain=.openiban.com; HttpOnly; SameSite=Lax
Location: https://openiban.comvalidate/DE89%203704%200044%200532%200130%2000?getBIC=true
CF-Cache-Status: DYNAMIC
cf-request-id: 03ad6fab50000040b0c030e200000001
Server: cloudflare
CF-RAY: 5ac28225496940b0-HAM
```
