### ISSUE TITLE
IBAN Calculation

### ISSUE THREAD

**Issue by sedrubal** [fourcube/goiban-service#2]
Do you still want to implement the IBAN calculation out of "Bankleihzahl"? I think this would be usefull, even if BLZs will be obsolete soon :tm:

**Comment by fourcube** [comment]
Hi and thanks for asking. This is still on my backlog, I might be able to implement this as an additional service endpoint before the start of the next year.

**Comment by fourcube** [comment]
Sorry for the slight delay. 

I've just pushed the new IBAN calculation functionality (both Service and UI) to openiban.com.

**Comment by sedrubal** [comment]
Hey cool, thanks ;)
