### ISSUE TITLE
Wrong BIC for single IBAN

### ISSUE THREAD

**Issue by tinu73** [fourcube/goiban-service#20]
Checked IBAN CH8904835125588551000 with https://www.iban.org/ and it returns correct BIC CRESCHZZ80A (Headquarter, Paradeplatz). Openiban returns wrong BIC CRESCHZZ81G (Opfikon-Glattbrugg)

**Comment by fourcube** [comment]
Thank you for reporting this.

I've done some research on the swiss IBAN structure. Since the branch codes do not uniquely map to a branch address, it is not possible to find the exact branch only by the IBAN number. 

If you have any hints on how to improve this lookup, please reopen this issue.
