### ISSUE TITLE
Replace -p with -port on start-page

### ISSUE THREAD

**Issue by dabpunkt** [fourcube/goiban-service#22]
Hello.

You tell people that they should start the stand-alone-binary with `-p 8080` but your binary says that it should be `-port 8080`.

Sincerely,
DaB.

P.S: Quite a shame that you stopped your webpage :-(

**Comment by fourcube** [comment]
Thank you for reporting this. Fixed in 5da638e69cfd00b1ed73d3a2b037c760f6a3776c.
