### ISSUE TITLE
Run service as a non-root user in Docker

### ISSUE THREAD

**Issue by verwilst** [fourcube/goiban-service#23]
Currently the service runs as root. I'm currently packaging OpenIBAN as a Helm chart at https://github.com/helm/charts . I could tighten security on the package a lot if i could disallow running as root by means of a PodSecurityPolicy. This is not possible yet for OpenIBAN. I'm unsure wether this project is still maintained, but rest assured that it's still very much in use, so although the service has been shut down, it would be said to see this project die completely. Could a user be added to the Docker image, and started as that user?

**Comment by verwilst** [comment]
Here you go! Just copy/paste into Dockerfile ;-)
```
FROM golang:alpine

WORKDIR /go/src/goiban-service
COPY ./*.go ./

RUN adduser -D openiban \
&& apk add --no-cache git \
&& go get -d -v ./... \
&& go install -v ./...

USER openiban

CMD ["/go/bin/goiban-service"]
```

**Comment by verwilst** [comment]
inside a running copy of that container:

```
/go/src/goiban-service $ ps aux
PID   USER     TIME  COMMAND
    1 openiban  0:00 /bin/sh
    9 openiban  0:01 /go/bin/goiban-service
   24 openiban  0:00 sh
   31 openiban  0:00 ps aux
```

**Comment by verwilst** [comment]
When you build a new image, please use `-t fourcube/openiban:1.0.1 -t fourcube/openiban:latest` (or whatever version is the next ;-)) and push both to Docker Hub, so we can track versions during Kubernetes deploys.

**Comment by fourcube** [comment]
Thanks @verwilst! I've just pushed the image to docker hub.
