### ISSUE TITLE
Nice way to start the service on reboot

### ISSUE THREAD

**Issue by inbaz** [fourcube/goiban-service#29]
Hey, 

is there already a nice way to start the service on reboot or do you just do a crontab 
```
@reboot /path/to/goiban/goiban-service -dataPath ./data -staticPath ./static -port 8080 -w
```

Andi

**Comment by fourcube** [comment]
@inbaz That should be fine. You could also use an upstart script like this one, which is fairly easy to tweak / convert to a systemd script. That would ensure that the service restarts in the unlikely event of a crash.

It expects the goiban binary to be located under /opt/openiban/goiban-service, and the data files under /opt/openiban/data. It also expects that an `openiban` user exists on the system.

```
Description "Openiban service"
author "Chris Grieger"

start on runlevel [2345]

setuid openiban
chdir /opt/openiban/goiban-service
exec ./goiban-service -dataPath ./data -port 8080 -w
respawn
respawn limit 10 90
```

If you need any more help, feel free to reopen this issue.

**Comment by inbaz** [comment]
Hey, thank you very much for your answer, I'll try that.
