### ISSUE TITLE
Inconsistent BIC format

### ISSUE THREAD

**Issue by kvdb** [fourcube/goiban-service#3]
A Belgian BIC comes out as: 'KRED BE BB', while Dutch BICs look like: 'RABONL2U'.
AFAIK, a BIC shouldn't include spaces.

**Comment by fourcube** [comment]
Thank you for reporting this issue.

I've just released an update. BICs should no longer contain spaces. https://github.com/fourcube/goiban-data-loader/commit/3a924d136ab40dee170a63209f5dfd04e3867b6c
