### ISSUE TITLE
Create Iban: Issue creating check code

### ISSUE THREAD

**Issue by bnc-rainman** [fourcube/goiban-service#5]
Hello,

if checkcode less then ten, the leading zero digit will be lost in the calculated result.
e.g.: IBAN: DE 03 BANKCODE 
   Calculater result: DE3BANKCODE

Best regards

**Comment by bnc-rainman** [comment]
Sorry, wrong project...
Project goiban  -> file iban.go -> line 95
	iban = strings.ToUpper(countryCode + result.String() + bankCode + account)
to 
	iban = strings.ToUpper(fmt.Sprintf("%s%02d%s%s", countryCode, result, bankCode, account))

i never write go before. Sorry for errors

**Comment by fourcube** [comment]
Thank you very much for reporting this!
