### ISSUE TITLE
Create Iban: leading zeros on account numbers

### ISSUE THREAD

**Issue by bnc-rainman** [fourcube/goiban-service#6]
Hello,

the REST Service Accepts German Account Numbers with less then ten digits. It would be nice to enlarge the account number with leading zeros.

Alternative return valid:false

Best regards

**Comment by fourcube** [comment]
Thank you for reporting this. 

It might be sensible to validate the generate IBAN by default and return a result similar to the one from the validation service. 

The response would then look exactly like the one from the validation service. Would that work for you?

**Comment by bnc-rainman** [comment]
This is a design decision. Both solution ways work for me.
I think your solution is cleaner and thus better,

**Comment by fourcube** [comment]
I've implemented automatic validation after generation of an IBAN. This new
functionality is available under the 'v2' namespace.

(e.g. /v2/calculate/<countryCode>/<bankCode>/<accountNumber>)
