### ISSUE TITLE
Having to manually accept the certificate

### ISSUE THREAD

**Issue by jcranky** [fourcube/goiban-service#7]
Hi,

I just switched to try and use the _https_ connection for _openiban_, but I'm getting this error:

```
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Does this mean that I'll have to manually add the _openiban_ certificate to the list of trusted certs? Or am I missing something else?

**Comment by fourcube** [comment]
Hi, 

thank you for reporting this issue. This seems to be a known with the certificates issued by letsencrypt and the Oracle JDK. 

Unfortunately it looks like the only fix is to manually add the certificate to the trust store. I just went ahead and switched back to the previous SSL certificate, which is supported much better. Until a recent JDK supports one of the letsencrypt root certificates, I'll stay with the Startcom cert.

Could you check if everything works now?

Cheers,
Chris

**Comment by jcranky** [comment]
Hi, I just tested it. Unfortunately, the _Startcom_ cert has the same issue :(

**Comment by fourcube** [comment]
Which version of the JDK are you using?

**Comment by jcranky** [comment]
1.8.0_77

**Comment by fourcube** [comment]
Unfortunately, it looks like java does neither support the letsencrypt, nor the startcom certificates.

Startcom have applied to be added to the Java root certificate list in 2011. But nothing has happened yet. 

It looks like the only solutions are to

a) Add the Startcom root certificates at runtime. (http://stackoverflow.com/a/2893932)
b) Add the Startcom root certifactes to the JVM keystore. (http://stackoverflow.com/a/2893932)
c) Add the Startcom root certificates to a keystore. (https://eknet.org/main/dev/startcom-keystore.html)

**Comment by jcranky** [comment]
All right, not ideal but will work, thank you. So should I work with the _Startcom_ one, or are you planning to change it back to the _letsencrypt_ one?

**Comment by fourcube** [comment]
Since both don't work with Java by default, I've just switched back to the letsencrypt certificate.

**Comment by jcranky** [comment]
Ok, thank you :)
