### ISSUE TITLE
How to get this service supporting more countries?

### ISSUE THREAD

**Issue by marbetschar** [fourcube/goiban-service#8]
Congrats to this service; it's just damn useful and using is a piece of cake!

Just wondering, if it will be extended to provide further information about IBAN's of other countries?
Basically I just want to retrieve the bank name of an IBAN number - ideally for every country.
But to start with, Switzerland would do it ;)

What do you need in order to extend the database to support additional countries and banking institutes?

**Comment by fourcube** [comment]
Thank you for your kind words!

I'd really like to support more countries and a contribution would be awesome. The easiest way for you to get openiban.com to provide the requested data would be to simply hook me up with the BIC / Bank data for all Swiss banks, preferably in plain text or XLSX format. (This data could be available on the website of the Swiss national bank) I can then extend the loader / parser logic and push an update to openiban.com.

To make these modifications yourself, you would have to fork the following repositories, perform some modifications and open a pull request:

- https://github.com/fourcube/goiban (for the country data and country specific data parsing rules)
- https://github.com/fourcube/goiban-data-loader (for loading the actual BIC data into backing MySQL database)

Unfortunately, I haven't gotten around to writing a comprehensive guide on how to a) setup the whole service for testing, b) extending the available bank data. This is definitely planned, but I cannot give any ETA on this.

Should you have any further questions, I'd be happy to help out!

**Comment by marbetschar** [comment]
https://www.six-interbank-clearing.com/de/home/bank-master-data/download-bc-bank-master.html

@fourcube does this work?

**Comment by fourcube** [comment]
This works for me! Thanks for looking this up. 

I've just added the Swiss bank data to openiban.com!

**Comment by marbetschar** [comment]
That's f*cking amazing!!!!! Thank you so much!!!!!!!
