### ISSUE TITLE
Belgian iban not working

### ISSUE THREAD

**Issue by Strikeh** [fourcube/goiban-service#9]
Hello, 

I think with the latest update something might gone wrong
https://openiban.com/validate/BE29001287409864?getBIC=true used to work.
Now I get the following response 
{
valid: true,
messages: [
"No BIC found for bank code: 001"
],
iban: "BE29001287409864",
bankData: {
bankCode: "",
name: ""
},
checkResults: { }
}

**Comment by fourcube** [comment]
Thanks you for reporting this! I've just fixed the issue.
